### ISSUE TITLE
Invalid name

### ISSUE THREAD

**Issue by farooqkz** [iraj-jelo/iraj.github.io#1]
to use Github pages(having a small website or anything, i think it's its name!) you should make a repository with name <username>.github.io
for you iraj-jelo.github.io
or it won't work.

**Comment by iraj-jelo** [comment]
I don't care . however it was worked as `iraj.github.io` before i did set it with [iraj.rocks](http://iraj.rocks)

**Comment by farooqkz** [comment]
ok
